package org.polyglotted.attributerepo.core;

import java.lang.reflect.Type;

/**
 * Represents a response generated by a remote Git action.
 * 
 * @author Shankar Vasudevan
 */
public interface Response {

    /**
     * return the status of the execution
     * 
     * @return int returning the status
     */
    int getStatusCode();

    /**
     * return the status of execution as a printable message
     * 
     * @return String returning the status
     */
    String getResponseStatus();

    /**
     * return any meta information available with the execution
     * 
     * @return String corresponding to a meta-header
     */
    String getMeta(String headerName);

    /**
     * return the result of execution typed to a class
     * 
     * @param type
     *            the type representing the result class
     * @return object representing the result properly parsed
     */
    <V> V getResult(Type type);
}
